# Default configuration settings
postgresql:
  host: localhost
  port: 5433 # Updated port
  database: sql1      # This is often a default database you can connect to.
  user: postgres          # This is often the default administrative user.
  password: pooja  # !!! YOU NEED TO REPLACE THIS !!!
  
mongodb:
  uri: mongodb://localhost:27017/
  database: converted_data

# Output settings
output:
  default_format: json
  output_dir: ./output
  
# Logging configuration
logging:
  level: INFO
  file: ./logs/conversion.log
